[build]
  base    = "Frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_GOOGLE_OAUTH_CLIENT_ID"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200


